# Generated by Django 4.0.3 on 2022-03-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_phone',
        ),
    ]
